### ISSUE TITLE
Standard port

### ISSUE THREAD

**Issue by kambrium** [michael-lazar/spartan#1]
Do you propose a standard TCP port a Spartan server should listen on?

**Comment by michael-lazar** [comment]
Yes, it's port 300!

> The default port for spartan URLs is 300, in reference to Battle of Thermopylae when 300 spartan soldiers stood ground against an invading Persian army.

I've also been thinking that the default for non-production or non-root servers should be 3000 (similar to how 8000 or 8080 are commonly used for HTTP). But that hasn't been added to the spec yet.
